#!/usr/bin/env ruby

# Load your rails app
require File.expand_path(File.dirname(__FILE__)) + '/../config/environment'

require 'rubygems'
require 'skynet'         

## See config/initializers/skynet.rb for more settings

Skynet::CONFIG[:LAUNCHER_PATH]    = File.expand_path(__FILE__)
# Skynet::CONFIG[:SKYNET_LOG_LEVEL] = Logger::INFO


Skynet.start
