#!/usr/bin/env ruby


require 'rubygems'
require 'skynet'         

# Require all files in lib
Dir["#{File.dirname(__FILE__)}" + "/../lib/**/*.rb"].each do |file|
  require file
end

Skynet::CONFIG[:LAUNCHER_PATH]    = File.expand_path(__FILE__)
# Skynet::CONFIG[:SKYNET_LOG_LEVEL] = Logger::ERROR
Skynet::CONFIG[:SKYNET_LOG_DIR]   = File.expand_path(File.dirname(__FILE__) + "/../log")
Skynet::CONFIG[:SKYNET_PID_DIR]   = File.expand_path(File.dirname(__FILE__) + "/../log")


Skynet.start
