#!/usr/bin/env ruby

<% if in_rails -%>
# Load your rails app
require File.expand_path(File.dirname(__FILE__)) + '/../config/environment'
<% end -%>
require 'rubygems'
require 'skynet'         

# Require any other libraries you want skynet to know about here

Skynet::CONFIG[:LAUNCHER_PATH]    = File.expand_path(__FILE__)
Skynet::CONFIG[:SKYNET_LOG_LEVEL] = Logger::ERROR
<% if not in_rails -%>
# Set your own configuration options here
Skynet::CONFIG[:SKYNET_LOG_DIR]   = File.expand_path(File.dirname(__FILE__) + "/../log")
Skynet::CONFIG[:SKYNET_PID_DIR]   = File.expand_path(File.dirname(__FILE__) + "/../log")
<% else -%>
## See config/initializers/skynet.rb for more settings
<% end -%>

<% if mysql -%>
<% if not in_rails -%>
# Use the mysql message queue adapter
Skynet::CONFIG[:MESSAGE_QUEUE_ADAPTER] = "Skynet::MessageQueueAdapter::Mysql"
Skynet::CONFIG[:MYSQL_HOST]            = "localhost"
Skynet::CONFIG[:MYSQL_USERNAME]        = "root"
Skynet::CONFIG[:MYSQL_PASSWORD]        = ""
Skynet::CONFIG[:MYSQL_DATABASE]        = "skynet"
<% end -%>
<% end -%>

# Start Skynet
Skynet.start
